name: temptrail
description: A CLI for Mac OS that uses AnyBar to show when your Mac is thermal throttling.
version: 1.2.0
homepage: https://github.com/jeroen-meijer/temptrail

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  args: ^1.6.0
  cli_util: ^0.2.0
  http: ^0.12.1
  intl: ^0.16.1
  meta: ^1.1.8

dev_dependencies:
  build_runner: ^1.10.0
  build_version: ^2.0.1
  import_sorter: ^4.1.0
  pedantic: ^1.9.0
